### ISSUE TITLE
BEDROCK_SERVER_ZIP_URL: parameter not set

### ISSUE THREAD

**Issue by xocoru** [skinlayers/docker-minecraft-bedrock#2] opened 2019-01-25 08:54 UTC
sorry, but i can't build
```
root@xoco-store:/volume1/storage/minecraft/docker-minecraft-bedrock# docker build -t minecraft-bedrock-server .
Sending build context to Docker daemon  134.7kB
Step 1/16 : FROM buildpack-deps:bionic-curl
bionic-curl: Pulling from library/buildpack-deps
Digest: sha256:25992d96688c6321125087b30a12313af169afff7177334baaf53fcf5bf7de5c
Status: Downloaded newer image for buildpack-deps:bionic-curl
 ---> 0fdce09ce7e1
Step 2/16 : ARG BEDROCK_SERVER_VERSION=1.8.1.2
 ---> Using cache
 ---> 93ceaeb3bdf0
Step 3/16 : ARG BEDROCK_SERVER_ZIP=bedrock-server-${BEDROCK_SERVER_VERSION}.zip
 ---> Using cache
 ---> 7870ceafcf69
Step 4/16 : ARG BEDROCK_SERVER_ZIP_URL=https://minecraft.azureedge.net/bin-linux/${BEDROCK_SERVER_ZIP}
 ---> Using cache
 ---> cacb1b2f943d
Step 5/16 : ARG BEDROCK_SERVER_ZIP_SHA256=bf04058f73e778833d8e7b508b571e7e150d7b42c4a7987780e89a9f5b1fe09f
 ---> Using cache
 ---> 7e197dc68b32
Step 6/16 : ARG BEDROCK_SERVER_ZIP_SHA256_FILE=${BEDROCK_SERVER_ZIP}.sha256
 ---> Using cache
 ---> e4038a7fc68f
Step 7/16 : RUN set -eu &&     groupadd -r -g 999 minecraft &&     useradd --no-log-init -r -u 999 -g minecraft -d /data minecraft &&     apt update && apt -y install unzip &&     curl -L "$BEDROCK_SERVER_ZIP_URL" -o "$BEDROCK_SERVER_ZIP" &&     echo "$BEDROCK_SERVER_ZIP_SHA256  $BEDROCK_SERVER_ZIP" > "$BEDROCK_SERVER_ZIP_SHA256_FILE" &&     sha256sum -c "$BEDROCK_SERVER_ZIP_SHA256_FILE" &&     unzip -q "$BEDROCK_SERVER_ZIP" -d minecraft &&     rm "$BEDROCK_SERVER_ZIP" "$BEDROCK_SERVER_ZIP_SHA256_FILE" &&     apt clean &&     rm -rf /var/lib/apt/lists/*
 ---> Running in 07c4b116e0b9

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:5 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [3451 B]
Get:6 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [310 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:8 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [140 kB]
Get:9 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]
Get:10 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:11 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Get:12 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [10.7 kB]
Get:13 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [638 kB]
Get:14 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [6955 B]
Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [910 kB]
Get:16 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [3666 B]
Fetched 15.4 MB in 5s (2865 kB/s)
Reading package lists...
Building dependency tree...
Reading state information...
All packages are up to date.

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
Suggested packages:
  zip
The following NEW packages will be installed:
  unzip
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 167 kB of archives.
After this operation, 558 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/main amd64 unzip amd64 6.0-21ubuntu1 [167 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 167 kB in 0s (386 kB/s)
Selecting previously unselected package unzip.
(Reading database ... 4748 files and directories currently installed.)
Preparing to unpack .../unzip_6.0-21ubuntu1_amd64.deb ...
Unpacking unzip (6.0-21ubuntu1) ...
Setting up unzip (6.0-21ubuntu1) ...
/bin/sh: 1: BEDROCK_SERVER_ZIP_URL: parameter not set
The command '/bin/sh -c set -eu &&     groupadd -r -g 999 minecraft &&     useradd --no-log-init -r -u 999 -g minecraft -d /data minecraft &&     apt update && apt -y install unzip &&     curl -L "$BEDROCK_SERVER_ZIP_URL" -o "$BEDROCK_SERVER_ZIP" &&     echo "$BEDROCK_SERVER_ZIP_SHA256  $BEDROCK_SERVER_ZIP" > "$BEDROCK_SERVER_ZIP_SHA256_FILE" &&     sha256sum -c "$BEDROCK_SERVER_ZIP_SHA256_FILE" &&     unzip -q "$BEDROCK_SERVER_ZIP" -d minecraft &&     rm "$BEDROCK_SERVER_ZIP" "$BEDROCK_SERVER_ZIP_SHA256_FILE" &&     apt clean &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 2
root@xoco-store:/volume1/storage/minecraft/docker-minecraft-bedrock#
```

**Comment by skinlayers** [comment] 2019-02-08 13:46
I have no idea why you're running into that error. The variable BEDROCK_SERVER_ZIP_URL is set near the top of the Dockerfile (see `Step 4/16` in your log above). I tested building the image again, and couldn't reproduce your issue. I've also just updated the Dockerfile to use Bedrock Server 1.9.0.15, and Docker Hub's automated builds are completing successfully: https://hub.docker.com/r/skinlayers/minecraft-bedrock-server/builds

What do you get if you run `docker version`? Build args were introduced in Docker 1.9 (11/2015), so if you have a really old version, that might be causing your build to fail.

```$ docker build -t minecraft-bedrock-server .
Sending build context to Docker daemon  177.7kB
Step 1/16 : FROM buildpack-deps:bionic-curl
 ---> 09b15921d5cb
Step 2/16 : ARG BEDROCK_SERVER_VERSION=1.8.1.2
 ---> Running in 2d267b9f3652
Removing intermediate container 2d267b9f3652
 ---> 921cb4b83f9c
Step 3/16 : ARG BEDROCK_SERVER_ZIP=bedrock-server-${BEDROCK_SERVER_VERSION}.zip
 ---> Running in 8c9697462ab7
Removing intermediate container 8c9697462ab7
 ---> 09eabc05465e
Step 4/16 : ARG BEDROCK_SERVER_ZIP_URL=https://minecraft.azureedge.net/bin-linux/${BEDROCK_SERVER_ZIP}
 ---> Running in f9870118e1c4
Removing intermediate container f9870118e1c4
 ---> 9c1ad6beb099
Step 5/16 : ARG BEDROCK_SERVER_ZIP_SHA256=bf04058f73e778833d8e7b508b571e7e150d7b42c4a7987780e89a9f5b1fe09f
 ---> Running in f7f6e5ef8220
Removing intermediate container f7f6e5ef8220
 ---> 427c6ee313a2
Step 6/16 : ARG BEDROCK_SERVER_ZIP_SHA256_FILE=${BEDROCK_SERVER_ZIP}.sha256
 ---> Running in f525776eac00
Removing intermediate container f525776eac00
 ---> 81e26def056e
Step 7/16 : RUN set -eu &&     groupadd -r -g 999 minecraft &&     useradd --no-log-init -r -u 999 -g minecraft -d /data minecraft &&     apt update && apt -y install unzip &&     curl -L "$BEDROCK_SERVER_ZIP_URL" -o "$BEDROCK_SERVER_ZIP" &&     echo "$BEDROCK_SERVER_ZIP_SHA256  $BEDROCK_SERVER_ZIP" > "$BEDROCK_SERVER_ZIP_SHA256_FILE" &&     sha256sum -c "$BEDROCK_SERVER_ZIP_SHA256_FILE" &&     unzip -q "$BEDROCK_SERVER_ZIP" -d minecraft &&     rm "$BEDROCK_SERVER_ZIP" "$BEDROCK_SERVER_ZIP_SHA256_FILE" &&     apt clean &&     rm -rf /var/lib/apt/lists/*
 ---> Running in f35f982380c9

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:3 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [339 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:6 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [3451 B]
Get:7 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [147 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Get:9 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:10 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:11 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]
Get:12 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [679 kB]
Get:13 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [10.7 kB]
Get:14 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [927 kB]
Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [6955 B]
Get:16 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [3666 B]
Fetched 15.5 MB in 5s (3235 kB/s)
Reading package lists...
Building dependency tree...
Reading state information...
4 packages can be upgraded. Run 'apt list --upgradable' to see them.

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
Suggested packages:
  zip
The following NEW packages will be installed:
  unzip
0 upgraded, 1 newly installed, 0 to remove and 4 not upgraded.
Need to get 167 kB of archives.
After this operation, 558 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/main amd64 unzip amd64 6.0-21ubuntu1 [167 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 167 kB in 1s (186 kB/s)
Selecting previously unselected package unzip.
(Reading database ... 4748 files and directories currently installed.)
Preparing to unpack .../unzip_6.0-21ubuntu1_amd64.deb ...
Unpacking unzip (6.0-21ubuntu1) ...
Setting up unzip (6.0-21ubuntu1) ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18.9M  100 18.9M    0     0  1926k      0  0:00:10  0:00:10 --:--:-- 2206k
bedrock-server-1.8.1.2.zip: OK

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Removing intermediate container f35f982380c9
 ---> 76c039625a9d
Step 8/16 : COPY ./docker-entrypoint.sh /
 ---> 32f388039307
Step 9/16 : WORKDIR /data
 ---> Running in 2bc729bb734c
Removing intermediate container 2bc729bb734c
 ---> 28e7bb378187
Step 10/16 : RUN cp /minecraft/server.properties . &&     cp /minecraft/whitelist.json . &&     touch ops.json &&     chown -R minecraft:minecraft /data &&     chmod +x /docker-entrypoint.sh
 ---> Running in ea4589bfd9b3
Removing intermediate container ea4589bfd9b3
 ---> ccc2550e5b06
Step 11/16 : EXPOSE 19132/udp        19132
 ---> Running in fa060bb650f2
Removing intermediate container fa060bb650f2
 ---> 66bc5886d252
Step 12/16 : USER minecraft
 ---> Running in 7e24e683a930
Removing intermediate container 7e24e683a930
 ---> ead318e98d55
Step 13/16 : ENV LD_LIBRARY_PATH=/minecraft
 ---> Running in fa29744f49cf
Removing intermediate container fa29744f49cf
 ---> 27b7915147e2
Step 14/16 : VOLUME ["/data"]
 ---> Running in 5114c4adf8d0
Removing intermediate container 5114c4adf8d0
 ---> cd0fd5a8c06a
Step 15/16 : ENTRYPOINT ["/docker-entrypoint.sh"]
 ---> Running in 8dbed9f00cf3
Removing intermediate container 8dbed9f00cf3
 ---> 982117331890
Step 16/16 : CMD ["/minecraft/bedrock_server"]
 ---> Running in 8aa6ce1d471a
Removing intermediate container 8aa6ce1d471a
 ---> bcfe986be1da
Successfully built bcfe986be1da
Successfully tagged minecraft-bedrock-server:latest
```

**Comment by skinlayers** [comment] 2019-02-08 13:49
I've also just updated to 1.9.0.15, and Docker Hub's automated builds are completing successfully: https://hub.docker.com/r/skinlayers/minecraft-bedrock-server/builds
```
Building in Docker Cloud's infrastructure...
Cloning into '.'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
Reset branch 'master'
Your branch is up-to-date with 'origin/master'.
KernelVersion: 4.4.0-1060-aws
Components: [{u'Version': u'18.03.1-ee-3', u'Name': u'Engine', u'Details': {u'KernelVersion': u'4.4.0-1060-aws', u'Os': u'linux', u'BuildTime': u'2018-08-30T18:42:30.000000000+00:00', u'ApiVersion': u'1.37', u'MinAPIVersion': u'1.12', u'GitCommit': u'b9a5c95', u'Arch': u'amd64', u'Experimental': u'false', u'GoVersion': u'go1.10.2'}}]
Arch: amd64
BuildTime: 2018-08-30T18:42:30.000000000+00:00
ApiVersion: 1.37
Platform: {u'Name': u''}
Version: 18.03.1-ee-3
MinAPIVersion: 1.12
GitCommit: b9a5c95
Os: linux
GoVersion: go1.10.2
Starting build of index.docker.io/skinlayers/minecraft-bedrock-server:latest...
Step 1/16 : FROM buildpack-deps:bionic-curl
---> 09b15921d5cb
Step 2/16 : ARG BEDROCK_SERVER_VERSION=1.9.0.15
---> Running in c54332843e2d
Removing intermediate container c54332843e2d
---> c5e2d993470a
Step 3/16 : ARG BEDROCK_SERVER_ZIP=bedrock-server-${BEDROCK_SERVER_VERSION}.zip
---> Running in fa61ff5d5f45
Removing intermediate container fa61ff5d5f45
---> 403e6708a95d
Step 4/16 : ARG BEDROCK_SERVER_ZIP_URL=https://minecraft.azureedge.net/bin-linux/${BEDROCK_SERVER_ZIP}
---> Running in 8b65f1f8948e
Removing intermediate container 8b65f1f8948e
---> 33b9cb890538
Step 5/16 : ARG BEDROCK_SERVER_ZIP_SHA256=560dca35fec3657caeabc2696c9458cdd8c649a2e232c9e00b8e9199af476191
---> Running in 9d89ab122fda
Removing intermediate container 9d89ab122fda
---> d470a2081581
Step 6/16 : ARG BEDROCK_SERVER_ZIP_SHA256_FILE=${BEDROCK_SERVER_ZIP}.sha256
---> Running in 2f527f00fe20
Removing intermediate container 2f527f00fe20
---> 2f60aed3549a
Step 7/16 : RUN set -eu && groupadd -r -g 999 minecraft && useradd --no-log-init -r -u 999 -g minecraft -d /data minecraft && apt update && apt -y install unzip && curl -L "$BEDROCK_SERVER_ZIP_URL" -o "$BEDROCK_SERVER_ZIP" && echo "$BEDROCK_SERVER_ZIP_SHA256 $BEDROCK_SERVER_ZIP" > "$BEDROCK_SERVER_ZIP_SHA256_FILE" && sha256sum -c "$BEDROCK_SERVER_ZIP_SHA256_FILE" && unzip -q "$BEDROCK_SERVER_ZIP" -d minecraft && rm "$BEDROCK_SERVER_ZIP" "$BEDROCK_SERVER_ZIP_SHA256_FILE" && apt clean && rm -rf /var/lib/apt/lists/*
---> Running in 71a24866478b
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
Get:1 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:2 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:5 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [339 kB]
Get:6 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [3451 B]
Get:7 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [147 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:9 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Get:10 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]
Get:11 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:12 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [6955 B]
Get:13 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [927 kB]
Get:14 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [10.7 kB]
Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [679 kB]
Get:16 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [3666 B]
Fetched 15.5 MB in 8s (1962 kB/s)
Reading package lists...
Building dependency tree...
Reading state information...
4 packages can be upgraded. Run 'apt list --upgradable' to see them.
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
Reading package lists...
Building dependency tree...
Reading state information...
Suggested packages:
zip
The following NEW packages will be installed:
unzip
0 upgraded, 1 newly installed, 0 to remove and 4 not upgraded.
Need to get 167 kB of archives.
After this operation, 558 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/main amd64 unzip amd64 6.0-21ubuntu1 [167 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 167 kB in 0s (356 kB/s)
Selecting previously unselected package unzip.
(Reading database ... (Reading database ... 5% (Reading database ... 10% (Reading database ... 15% (Reading database ... 20% (Reading database ... 25% (Reading database ... 30% (Reading database ... 35% (Reading database ... 40% (Reading database ... 45% (Reading database ... 50% (Reading database ... 55% (Reading database ... 60% (Reading database ... 65% (Reading database ... 70% (Reading database ... 75% (Reading database ... 80% (Reading database ... 85% (Reading database ... 90% (Reading database ... 95% (Reading database ... 100% (Reading database ... 4748 files and directories currently installed.)
Preparing to unpack .../unzip_6.0-21ubuntu1_amd64.deb ...
Unpacking unzip (6.0-21ubuntu1) ...
Setting up unzip (6.0-21ubuntu1) ...
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
39 18.9M 39 7673k 0 0 9.8M 0 0:00:01 --:--:-- 0:00:01 9.8M
100 18.9M 100 18.9M 0 0 13.1M 0 0:00:01 0:00:01 --:--:-- 13.1M
bedrock-server-1.9.0.15.zip: OK
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
Removing intermediate container 71a24866478b
---> 8b7ef8542560
Step 8/16 : COPY ./docker-entrypoint.sh /
---> f5cc18f434c8
Step 9/16 : WORKDIR /data
Removing intermediate container 7a46b63ecbe8
---> 7bd79b1742ff
Step 10/16 : RUN cp /minecraft/server.properties . && cp /minecraft/whitelist.json . && touch ops.json && chown -R minecraft:minecraft /data && chmod +x /docker-entrypoint.sh
---> Running in 9d55ddfc53a4
Removing intermediate container 9d55ddfc53a4
---> 14d6b2cc7c04
Step 11/16 : EXPOSE 19132/udp 19132
---> Running in 0f2c970778b5
Removing intermediate container 0f2c970778b5
---> cbcc0557c644
Step 12/16 : USER minecraft
---> Running in 5c141f4bfcde
Removing intermediate container 5c141f4bfcde
---> 8140b8db4baf
Step 13/16 : ENV LD_LIBRARY_PATH=/minecraft
---> Running in 9aab11a71ad0
Removing intermediate container 9aab11a71ad0
---> 123937f74b00
Step 14/16 : VOLUME ["/data"]
---> Running in 5b25df78b2e6
Removing intermediate container 5b25df78b2e6
---> bddc0fe5415a
Step 15/16 : ENTRYPOINT ["/docker-entrypoint.sh"]
---> Running in 377e6a513dd8
Removing intermediate container 377e6a513dd8
---> 88ec15a8ac61
Step 16/16 : CMD ["/minecraft/bedrock_server"]
---> Running in 481b247bbeca
Removing intermediate container 481b247bbeca
---> ef69a7b61b43
Successfully built ef69a7b61b43
Successfully tagged skinlayers/minecraft-bedrock-server:latest
Pushing index.docker.io/skinlayers/minecraft-bedrock-server:latest...
Done!
Build finished
```

**Comment by xocoru** [comment] 2019-02-08 14:32
I think it could be cause i do it on Synology NAS. 

I will try to not build it by myself from command line and use repository - https://hub.docker.com/r/skinlayers/minecraft-bedrock-server .

**Comment by skinlayers** [comment] 2019-11-07 20:35
Closing this issue as I have been unable to reproduce it.

**Closed as completed by skinlayers** 2019-11-07 20:35 UTC
